// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pqtctzedwusznzpotxpq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBxdGN0emVkd3Vzem56cG90eHBxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkyMzI4ODMsImV4cCI6MjA3NDgwODg4M30.cAfTauemJWyfjx_YOzmmO8r-qaf2DszFs5bbDbr6mkA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});